### ISSUE TITLE
Client secret is a hard coded?

### ISSUE THREAD

**Issue by IgorDePaula** [andreroggeri/pynubank#320]
https://github.com/andreroggeri/pynubank/blob/master/pynubank/nubank.py#L58

**Comment by andreroggeri** [comment]
Not so secret eh ?

It can be found on [their website](https://app.nubank.com.br/scripts/scripts.js) (search for this secret)

**Comment by IgorDePaula** [comment]
https://docs.nupaybusiness.com.br/#/checkout/?id=credenciais

**Comment by andreroggeri** [comment]
Thats a different API.

This is a thin wrapper around the APIs used for the web app and the mobile app

**Comment by andreroggeri** [comment]
If you have any questions please let me know.

**Comment by IgorDePaula** [comment]
Ok, I only want make an alert security of your code.

**Comment by andreroggeri** [comment]
But what is the problem ? The client secret is the same used by the Nubank official webapp (The link that I sent you on the first reply)

I don't see any way to make this work without this secret (Client secrets are not so secret because anyone can decompile, instrument or inspect requests to get it)
